services:
  garage:
    image: dxflrs/garage:v0.9.0
    restart: unless-stopped
    environment:
      GARAGE_RPC_SECRET: "1799bccfd7411abb9cc9a3f8c0c72caf4bf427e5e4041c057c3254ca42b9e6c5"
      GARAGE_METADATA_DIR: "/data/meta"
      GARAGE_DATA_DIR: "/data/data"
      GARAGE_DB_ENGINE: "lmdb"
      GARAGE_REPLICATION_MODE: "1"
      GARAGE_RPC_BIND_ADDR: "[::]:3901"
      GARAGE_RPC_PUBLIC_ADDR: "127.0.0.1:3901"
      GARAGE_S3_REGION: "garage"
      GARAGE_S3_API_BIND_ADDR: "[::]:3900"
      GARAGE_S3_WEB_BIND_ADDR: "[::]:3902"
      GARAGE_ADMIN_API_BIND_ADDR: "[::]:3903"
      GARAGE_ADMIN_TOKEN: "EC6DBE9717A36965EECAB130793557522A0D9CB20F13B9EAC646F0F6004D97D0"
      GARAGE_METRICS_TOKEN: "5DF6E2573F649C0A6A21D596A9E74B864282CB169732130C1192D093AEB703B0"
    volumes:
      - garage_data:/data
    expose:
      - "3900"
      - "3902" 
      - "3903"

volumes:
  garage_data: