metadata_dir = "/metadata"
data_dir = "/data"
db_engine = "lmdb"

replication_mode = "1"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
# rpc_secret will be read from environment variable GARAGE_RPC_SECRET

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.jeth.ovh"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.jeth.ovh"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
# admin_token and metrics_token will be read from environment variables

[consul_discovery]
consul_http_addr = ""
service_name = ""
ca_cert = ""
client_cert = ""
client_key = ""
tls_skip_verify = false
tags = []
meta = {}

[kubernetes_discovery]
namespace = ""
service_name = ""
skip_crd = false